# This is a basic workflow to help you get started with Actions

name: Storybook_Automation

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    paths:
      - 'storybook/**'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
   inputs:
      story_title:
        description: 'A short title for the story'
        required: true
        default: 'Default Title'
      author_name:
        description: 'The author''s name'
        required: true
        default: 'Anonymous'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Create Story
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo "Once upon a time in a faraway land"
          echo "${{ github.event.inputs.story_title }} was written by ${{ github.event.inputs.author_name }}"
          echo "This whimsical tale takes you on a journey through a magical forest where every flower could talk."
          echo "Will you explore its secrets?"